'use client';
import {useEffect,useState,FormEvent} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Doc={id:string;name:string;page_count:number;sha256:string};
type Fact={property:string;raw_value:string;normalized_value:string|null;page:number;exact_quote:string;evidence_valid:boolean};
type Change={property:string;state:string;old:Fact|null;new:Fact|null;confirmed:boolean|null};
type Decision={id:string;title:string;property:string;status:string};
type Result={id:string;old_id:string;new_id:string;model:string;changes:Change[];decisions:Decision[]};
const fields=['product_identity','thickness','density','declared_grade','usage_conditions','application_limits','certificate_reference','revision_date'];
export default function Home(){
 const [docs,setDocs]=useState<Doc[]>([]),[oldId,setOld]=useState(''),[newId,setNew]=useState(''),[provider,setProvider]=useState('mock');
 const [result,setResult]=useState<Result|null>(null),[decisions,setDecisions]=useState<Decision[]>([]),[title,setTitle]=useState(''),[property,setProperty]=useState('usage_conditions');
 const [token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[info,setInfo]=useState('');
 async function request<T>(path:string,options:RequestInit={}):Promise<T>{const headers:{[key:string]:string}={...(options.headers as Record<string,string>||{})};if(token)headers['X-Write-Token']=token;const res=await fetch(API+path,{...options,headers,cache:'no-store'});if(!res.ok){const e=await res.json().catch(()=>({detail:res.statusText}));throw new Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail))}return res.json()}
 async function refresh(){try{const [d,dec]=await Promise.all([request<Doc[]>('/documents'),request<Decision[]>('/decisions')]);setDocs(d);setDecisions(dec);if(d.length>1){setOld(v=>v||d[1].id);setNew(v=>v||d[0].id)}}catch(e){setError(String(e))}}
 useEffect(()=>{refresh()},[]); // initial read-only loading
 async function run(fn:()=>Promise<void>){setError('');setInfo('');setBusy(true);try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget;const file=(new FormData(el)).get('file');if(!(file instanceof File))return;await run(async()=>{const body=new FormData();body.append('file',file);const d=await request<Doc>('/documents',{method:'POST',body});setInfo('Uploaded '+d.name);el.reset();await refresh()})}
 async function compare(){await run(async()=>{const r=await request<Result>('/comparisons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({old_id:oldId,new_id:newId,provider})});setResult(r);setInfo('Comparison complete. Check evidence before confirming changes.')})}
 async function addDecision(e:FormEvent<HTMLFormElement>){e.preventDefault();await run(async()=>{await request('/decisions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,property})});setTitle('');await refresh();setInfo('Decision created. It references the selected property.')})}
 async function review(index:number,confirmed:boolean){if(!result)return;await run(async()=>{const r=await request<Result>('/comparisons/'+result.id+'/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({change_index:index,confirmed})});setResult(r);await refresh()})}
 async function loadComparison(id:string){await run(async()=>setResult(await request<Result>('/comparisons/'+id)))}
 const [history,setHistory]=useState<{id:string;model:string}[]>([]);
 async function loadHistory(){await run(async()=>{setHistory(await request<{id:string;model:string}[]>('/comparisons'))})}
 return <main><header><div><div className="eyebrow">Engineering evidence intelligence · Portfolio MVP</div><h1>TraceDelta <span style={{color:'#65e2bf'}}>↗</span></h1><div className="muted">From revised material documents to accountable human review.</div></div><span className="pill">Synthetic demo · Not for structural design</span></header>
 <section className="card"><h2>Start here</h2><p className="muted">Upload the supplied synthetic V1/V2 PDFs. In mock mode, comparison requires no API key. Gemini mode requires a configured backend key and available model.</p><div className="grid"><div><form onSubmit={upload}><label>Upload digital PDF (max 10 MB, 10 pages)</label><input name="file" type="file" accept="application/pdf" required/><button disabled={busy}>Upload document</button></form></div><div><label>Owner write token (only if enabled on the backend)</label><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Never place the token in public frontend env"/><p className="muted">The token is kept only in this browser session state.</p></div></div></section>
 {error&&<p className="notice" role="alert">{error}</p>}{info&&<p className="pill" role="status">{info}</p>}
 <div className="grid"><section className="card"><h2>Compare revisions</h2><label>Reviewed baseline</label><select value={oldId} onChange={e=>setOld(e.target.value)}><option value="">Choose document</option>{docs.map(d=><option key={d.id} value={d.id}>{d.name} ({d.page_count}p)</option>)}</select><label>New revision</label><select value={newId} onChange={e=>setNew(e.target.value)}><option value="">Choose document</option>{docs.map(d=><option key={d.id} value={d.id}>{d.name} ({d.page_count}p)</option>)}</select><label>Extractor</label><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="mock">Mock / local rules (no API)</option><option value="gemini">Gemini (real API)</option></select><button disabled={busy||!oldId||!newId||oldId===newId} onClick={compare}>Run comparison</button></section>
 <section className="card"><h2>Decision dependencies</h2><p className="muted">Create an explicit dependency on a material property. Confirmed changes flag related decisions for review.</p><form onSubmit={addDecision}><label>Decision description</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Review suitability of panel for SC2" required maxLength={160}/><label>Referenced property</label><select value={property} onChange={e=>setProperty(e.target.value)}>{fields.map(f=><option key={f} value={f}>{f}</option>)}</select><button disabled={busy}>Save dependency</button></form>{decisions.map(d=><p key={d.id}><span className={d.status==='needs_review'?'pill warn':'pill'}>{d.status}</span> {d.title} <span className="tag">({d.property})</span></p>)}</section></div>
 <section className="card"><div className="pair"><h2>Review comparison</h2><button className="secondary" onClick={loadHistory} disabled={busy}>Load history</button></div>{history.length>0&&<div className="buttons">{history.map(h=><button className="secondary" key={h.id} onClick={()=>loadComparison(h.id)}>{h.id.slice(0,8)} · {h.model}</button>)}</div>}{!result?<p className="muted">Run a comparison or load a previous result. Evidence and change status appear here.</p>:<><div className="buttons"><span className="pill">{result.model}</span><a className="btn secondary" href={API+'/comparisons/'+result.id+'/export?format=json'} target="_blank">Export JSON ↗</a><a className="btn secondary" href={API+'/comparisons/'+result.id+'/export?format=html'} target="_blank">Printable report ↗</a></div><table><thead><tr><th>Property</th><th>Baseline evidence</th><th>Revised evidence</th><th>Result</th><th>Human review</th></tr></thead><tbody>{result.changes.map((c,i)=><tr key={i}><td><strong>{c.property.replaceAll('_',' ')}</strong></td>{([c.old,c.new] as (Fact|null)[]).map((f,idx)=><td key={idx}>{f?<><div>{f.raw_value}</div><small className="muted">Page {f.page} · quoted text validated</small><p className="muted">“{f.exact_quote}”</p><a target="_blank" href={API+'/documents/'+(idx===0?result.old_id:result.new_id)+'/pdf#page='+f.page}>View PDF ↗</a></>:<span className="muted">Not extracted</span>}</td>)}<td><span className={c.state==='changed'?'pill warn':c.state==='unresolved'?'pill danger':'pill'}>{c.state}</span></td><td>{c.confirmed===null && c.state!=='unchanged'?<div className="buttons"><button disabled={busy} onClick={()=>review(i,true)}>Confirm</button><button className="secondary" disabled={busy} onClick={()=>review(i,false)}>Reject</button></div>:c.confirmed===null?'—':<span className="pill">{c.confirmed?'Confirmed':'Rejected'}</span>}</td></tr>)}</tbody></table><p className="notice">Verified quote location ≠ verified semantic interpretation. Compare in context before approval.</p></>}</section>
 <footer className="muted">TraceDelta · Independent portfolio project. No affiliation with SPEC Toolbox. Synthetic documents only.</footer></main>
}
